Use git bundle instead of patch
wvchallenges/se-challenge-payroll pull request #1
Opened 2017-01-26 19:57 UTC by Incognito

Ask candidates to submit a git bundle. https://git-scm.com/docs/git-bundle

On our side we simply download this file and can run: `git clone <bundle_file> <target_directory>`.

This creates the entire repo with commit history.

It might be worth doing a test run to see if email spam filters block sending bundle files around.

2017-01-26 20:23 UTC, jimgraham requested changes
opportunity to clean up typos/instructions. Thx.

2017-01-26 20:23 UTC, jimgraham commented on README.md
>  1. Complete your project as described below within your local repository.
`s/below/above/`

2017-01-26 20:23 UTC, jimgraham commented on README.md
> +it in a way that showcases one of your strengths. If you you enjoy front-end
`s/you you/you/`

2017-02-08 18:35 UTC, ashchristopher approved these changes

2017-02-08 18:36 UTC, merged